common: &common
  adapter: postgresql
  host: localhost
development:
  <<: *common
  database: cathat_dev

test:
  <<: *common
  database: cathat_test

production:
  <<: *common
  username: supercat
  password: supercat-qwertyuiop
  database: cathat_prod
